org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Project versions
projectGroup=io.github.17theword.queqiao
artifactId=core
projectVersion=0.7.0-beta.2
name=QueQiao Core
description=Cross-platform Minecraft server communication framework for plugins and mods
url=https://github.com/17TheWord/queqiao-tool
githubRepository=17TheWord/queqiao-tool
developerId=17theword
developerName=17TheWord
# Lib versions
gsonVersion=2.8.0
glavoRconVersion=3.0
lombokVersion=1.18.30
snakeyamlVersion=2.0
slf4jApiVersion=1.7.25
commonsIoVersion=2.15.1
slf4jSimpleVersion=1.7.25
javaWebSocketVersion=1.5.3
junitJupiterApiVersion=5.13.4
junitJupiterPlatformLauncherVersion=1.13.4
